### ISSUE TITLE
Move lua scripts out of CT files

### ISSUE THREAD

**Issue by ngc92** [J-T-de/CrusaderData#1]
For better maintainability, I would recommend to move the lua scripts outside of the Cheat Tables, and just put the corresponding imports there. That way you can use whatever code editor you like, split the scripts into separate modules, and can browse the code on Github

**Comment by J-T-de** [comment]
I agree, this just went too fast too big and I didn't bother to split it. Thanks for the recommendation. Done with commit https://github.com/J-T-de/CrusaderData/commit/1618436c192106c78d879d0a49b2542b43d7ca6a.
